### ISSUE TITLE
Unable to get the game to open

### ISSUE THREAD

**Issue by GazzaLinks** [AcidCaos/raisetheempires#9]
Hi.

I'm not sure if this is the right place to post this query, so sorry if I should be asking this elsewhere. I'm currently unable to get the latest version of the game (alpha 0.06a) to run on my PC. I'm running Windows 7 Pro and am confident my specs are good enough given I used to be able to run the game without any issues when it was still on Facebook. Attempting to open the game results in a command line interface window opening for a moment before it then closes, nothing happening afterwards. This is the first time I have tried to install any version of the game.

The most likely reason for this, I think, is that installing the game requires Microsoft Visual C++ to also be installed. However, installing this program failed as I already have it installed, meaning that my best guess for why I can't run the game is that I don't have the right version on my PC. Do I need to specifically have the version of Microsoft Visual C++ that automatically tries to install when first installing Raise the Empires?

Any help or advice would be much appreciated, thanks.

**Comment by Questandachievement7Developer** [comment]
Hi, for Windows 7 installation this problem is quite common, you might want to try this update package before installing https://www.microsoft.com/en-us/download/details.aspx?id=26764

**Comment by GazzaLinks** [comment]
> Hi, for Windows 7 installation this problem is quite common, you might want to try this update package before installing https://www.microsoft.com/en-us/download/details.aspx?id=26764

Thanks for replying. I clicked on the link but apparently the download is no longer present. Is there another way to get it?

**Comment by Willy030125** [comment]
> > Hi, for Windows 7 installation this problem is quite common, you might want to try this update package before installing https://www.microsoft.com/en-us/download/details.aspx?id=26764
> 
> Thanks for replying. I clicked on the link but apparently the download is no longer present. Is there another way to get it?

Yes, check it here: https://web.archive.org/web/20200611094821/https://www.microsoft.com/en-us/download/details.aspx?id=26764

**Comment by GazzaLinks** [comment]
Thanks for your help so far, everyone.

I think it's almost working. I've managed to get as far as the screen below, however, pressing the play now button results in an endless loading symbol appearing the top left corner of the screen.

![image](https://user-images.githubusercontent.com/71219888/93584448-399d1900-f99d-11ea-8aa1-215e7cf81829.png)

Below is what I'm seeing in the command line interface window currently:

Gamesettings loaded:  133  setting sections loaded
Initial island template 507 objects loaded 32 roads loaded
Ally islands 5 allies loaded 409 objects loaded 191 roads loaded
Questsettings loaded:  1662  quests loaded
C:\Users\Graeme\Documents\My Games\RaiseTheEmpires\save.db
True
2020-09-18 10:36:26,667 [10692] [00;36mINFO     engineio.server: Server initialized for threading.[0m
2020-09-18 10:36:26,676 [10692] [01;33mWARNING  py.warnings: site-packages\flask_sqlalchemy\__init__.py:833: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
[0m
2020-09-18 10:36:26,679 [10692] [01;33mWARNING  werkzeug: WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.[0m
 * Serving Flask app "empires-server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-09-18 10:36:26,699 [10692] [00;36mINFO     werkzeug:  * Running on http://127.0.0.1:5005/ (Press CTRL+C to quit)[0m
2020-09-18 10:36:30,370 [10692] [00;36mINFO     werkzeug: 127.0.0.1 - - [18/Sep/2020 10:36:30] "[37mGET / HTTP/1.1[0m" 200 -[0m
home
2020-09-18 10:36:42,275 [10692] [01;31mERROR    empires-server: Exception on /home.html [GET][0m
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 2447, in wsgi_app
  File "site-packages\flask\app.py", line 1952, in full_dispatch_request
  File "site-packages\flask\app.py", line 1821, in handle_user_exception
  File "site-packages\flask\_compat.py", line 39, in reraise
  File "site-packages\flask\app.py", line 1950, in full_dispatch_request
  File "site-packages\flask\app.py", line 1936, in dispatch_request
  File "empires-server.py", line 112, in home
  File "empires-server.py", line 123, in get_allies_friend
  File "empires-server.py", line 193, in get_sessions_friends
  File "empires-server.py", line 202, in <listcomp>
  File "save_engine.py", line 133, in validate_save
AttributeError: 'NoneType' object has no attribute 'get'
2020-09-18 10:40:01,640 [10692] [00;36mINFO     werkzeug: 127.0.0.1 - - [18/Sep/2020 10:40:01] "[37mGET /home.html HTTP/1.1[0m" 200 -[0m

Any further help would be great if anyone knows what I'm doing wrong.

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
